name: tenlittleendians
favicon: null
layout_spectrum: 0.7563730024266988
typography_spectrum: 0.35786372632719576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22775174118578434
  lightness: 0.20426241331733763
  saturation: 0.7649986450560391
  rhythmicContrast: 0.7200669359881431
purpose: []
